const MIN_CLICKABLE_SIZE_RETINA = 44;

export const MIN_CLICKABLE_SIZE = MIN_CLICKABLE_SIZE_RETINA / 2;

export const DEFAULT_BORDER_RADIUS = 10;

export const TRANSITION_DURATION = "0.3s";

export const TRANSITION_TIMING = "cubic-bezier(0.645, 0.045, 0.355, 1.000)";
